apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: navique-ai-core-operator
  name: navique-ai-core-operator-clickhousecluster-admin-role
rules:
- apiGroups:
  - core.navique.com
  resources:
  - clickhouseclusters
  verbs:
  - '*'
- apiGroups:
  - core.navique.com
  resources:
  - clickhouseclusters/status
  verbs:
  - get
