apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sbr-operator-sbr-agent-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - storage-based-remediation.medik8s.io
  resources:
  - storagebasedremediationconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage-based-remediation.medik8s.io
  resources:
  - storagebasedremediationconfigs/status
  verbs:
  - get
- apiGroups:
  - storage-based-remediation.medik8s.io
  resources:
  - storagebasedremediations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage-based-remediation.medik8s.io
  resources:
  - storagebasedremediations/status
  verbs:
  - get
  - patch
  - update
