apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbr-operator
  name: sbr-operator-storagebasedremediationtemplate-admin-role
rules:
- apiGroups:
  - storage-based-remediation.medik8s.io
  resources:
  - storagebasedremediationtemplates
  verbs:
  - '*'
- apiGroups:
  - storage-based-remediation.medik8s.io
  resources:
  - storagebasedremediationtemplates/status
  verbs:
  - get
