apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: sbr-operator
    app.kubernetes.io/name: sbr-agent
    app.kubernetes.io/part-of: sbr-operator
  name: sbr-operator-sbr-agent
