apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: sbr-operator
    app.kubernetes.io/name: sbr-agent
    app.kubernetes.io/part-of: sbr-operator
  name: sbr-operator-sbr-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sbr-operator-sbr-agent-role
subjects:
- kind: ServiceAccount
  name: sbr-operator-sbr-agent
  namespace: sbr-operator-system
