apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: langfuse-operator
  name: langfuse-operator-langfuseproject-viewer-role
rules:
- apiGroups:
  - langfuse.palena.ai
  resources:
  - langfuseprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - langfuse.palena.ai
  resources:
  - langfuseprojects/status
  verbs:
  - get
