apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oc-mirror
  name: oc-mirror-manager-pod-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oc-mirror-manager-pod-role
subjects:
- kind: ServiceAccount
  name: oc-mirror-manager
  namespace: oc-mirror-system
