apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-emrserverless-reader
rules:
- apiGroups:
  - emrserverless.services.k8s.aws
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
