apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: decision-model-operator
  name: decision-model-operator-decisionmodel-viewer-role
rules:
- apiGroups:
  - decisionmodel.io
  resources:
  - decisionmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - decisionmodel.io
  resources:
  - decisionmodels/status
  verbs:
  - get
