# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "camel.apache.org/v1alpha1",
          "kind": "CamelMonitor",
          "metadata": {
            "labels": {
              "app": "camel-monitor-operator"
            },
            "name": "example"
          },
          "spec": {}
        }
      ]
    capabilities: Full Lifecycle
    categories: Observability
    certified: "false"
    containerImage: quay.io/camel-tooling/camel-monitor-operator:0.2.1
    createdAt: "2026-06-03T08:01:40Z"
    description: Camel Monitor Operator is the monitoring tool for your Apache Camel
      applications running on cloud.
    operators.operatorframework.io/builder: operator-sdk-v1.30.0
    operators.operatorframework.io/internal-objects: '["camelmonitors.camel.apache.org"]'
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    repository: https://github.com/camel-tooling/camel-monitor-operator
    support: Camel
  name: camel-monitor-operator.v0.2.1
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CamelMonitor is the Schema for the CamelMonitor API
      displayName: CamelMonitor
      kind: CamelMonitor
      name: camelmonitors.camel.apache.org
      version: v1alpha1
  description: |
    Camel Monitor Operator is the monitoring tool for your Apache Camel applications running on cloud.
    ## Installation
    Proceed to the Camel Monitor operator installation via `Subscription` or via GUI.
    See official Camel Monitor operator documentation to learn how to configure all the available parameters.
    ## Monitoring an Apache Camel Application
    Run an Apache Camel application on the cluster (for example via Apache Camel K operator). Immediately you will be able to see a `CamelMonitor`:

    ```
    kubectl get camelmonitors -w

    NAME        INFO                        PHASE     REPLICAS   HEALTHY   MONITORED   MEMORY PRESSURE   CPU PRESSURE   EXCHANGE SLI   LAST EXCHANGE
    sample-it   Quarkus - 3.30.8 (4.16.0)   Running   1          True      True        False             False          Success        1s
    sample-it   Quarkus - 3.30.8 (4.16.0)   Paused    0          Unknown   Unknown                                      Success        61s
    ...
    ```
  displayName: Camel Monitor Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfqARsJNB/4gK7nAAALq0lEQVR42u2bW2xcxRnHfzPn7N33dXzPndS5Q5NwCUmgUBoCIlAQpUAC5VrUh1YVJZV4aeGlEkJVpQoeqkILiFAoLYWGiIIIF4HaJFwKTgONHSdgp3HsbHxde9d7OdOHnV0fr9f2+vgS1O5fWq/P2d05M7/zfd/MfDMHCiqooIIKKqigggoqqKCCZlzibF14+3WvjV8pAUqNHO955aqzVc25AzQREMAE3Po9KQVxIGap3F+eS2CzDigHGBNoAFYBq4ElQA1QBniBGBAGOoFmoAn4DGgDEnMNatYA5QBTA1wObAcuBOq11UymGNABfADsBd4ATs4VqBkHlANMA7ATuEVbjTGN4i3gc+A5YDfw5WyDmlFAWXA8wI3ALuDcXN9XCpRSowJypmIChBCI8Wt4GPiVhhWZLUgzBigLTgPwc2053mwolqUwTUlJiUll0Et5uZtAkYnHLYnFFYPhON09MUKhYQYG4sTjFlLmhBUHntfXOj4bkGYEUBacdcCvgU2jwShAUFnpYfWqMtasKWfRwiIqKtx4PAaGITLdu2UpotEkPT0xjn8Rpqmph8Of9RIKDQMKMZbUQeBHwIGZhjRtQFlwNgO/AVbaT1qWorraxyVbqtl08Txqa/2YpsjbxRIJi1Onouw/cJp33j1FR0ckl/u1APcC784kpGkByoKzAXgWaEyfUArcbsmmi6vYfk0DDQ1+hBBY4w1wJpCUKaAnTw6x59V23nu/i1jMygXpdmD/TEGaTo9C4/Kd6X8XAk8C56VPWJairMzNjluXcMP1C6io8GiLcXat9O9KS92sXVtBRYWb1tYwkUjC7nJB7eJvA90AzUd2nx1ANusJ6N7kajucefO83HvPMrZsrsIwhGMwuUAZhmDJ4mLq6/w0t/QTDo+CVAvUAa8BscblO6cFSc5Ane8AvjvSAEUw6OHeu5dx/obKya1GSJBGytuFSB2LiT0/Xeb69UHuvmtZxjptuh64WyEQQk02zZlQjizIdsFG4DFt2igFXq/J7bctZePGqjxijSAeOkr81GFkIIiKhUn2nUAl40h3kYaVidhjwCkFdbV+iotdNB3qIZFQ6a8IoFHA6yBCTMPVTMdoU7pHz6Uy+ublNWzelA+cVMOHDu8h8snzuOdvIBnpxeo/ifSW4FtxNb5V2xGmD6wEKAukifSVpSxOm4xSis2bqmhtHeD1N0bNQBYD3wd+Ajh28Cn3YjbrWQG8DsxHx52lS4rZtWsVwQqvHvdMImkQbdlH394HsWJD2kKEHutIjNJ6hMuLSsbBSiJMD+6FFxJYfxtGSV0Kmu7hTp2K8Mij/6K9fRApM806AWzV0xNHPdp0LOiGNBwA05Rs3VpHZdCbfzeuFFa0F5SFkNJ2v1IjxmRPW9a9VCRON2MNdFJ65cMIT1GqDEtRU+Nj6xW1PPVMqz0eNQDXpgE5kdMgXaZn5aCtZ/GiIjasD+ZnObrBVrSPSNPLqHh0BI49qgtpe+kAjkHs6LsMffoiWJaNteKCC+ZRX+/PvkHbgZI5AWRzrzV6Zp5qhxBs2BCktNSdf3cuJMneEyS7j2vXUhOGCqUUykqCUqh4jMihV0gOhTKBWymoqHCzfl0w+6er0oNXJ72ZUws6HyhKV6woYLJ2TfnUShBgRbpRiYh2KW08YuSVKt9CKQujfAG+c2/ErF2NKK7Cu+IqpLds1BhCCMHateX4fKMiR5l9ADtVOYlBAvh6+kCplP/X1Pqm4F76t4loJtCO/VChEBil9XgWb8Z/3k24KpeRHDqDFe3DLJuPkK5RVqeUor7eT2XQQ/uJUcF6TgEF7F27UlBX58PvM6c4Wha6+9bddabA1B/pLcW/bge+FdswSxtAmqAsjEAQI1CpwY6+YMqaXVRXe2lrH7R/tEhnL2NzAagIqMw0U0BVlQ/DcDAJtRJjwk7qnkv863ZQvPE+vcRhjViamjhWuVyCmhpf9ulKW757SnISgwL6pQEJykpdk80OckhhxYZSMWbUaYXwl+H92uWpXms8FxyvQVJQUjKmPsXZibvZBOSyW54Q4HI7KEYpEr0nUGMAKKSnJBWAmRqctNxumQ3IcNohTXuyqhQkk5O7lkrG9FjGQEiT5EAnw20Hc30T4Q4gTI/jCUIsZs1Y9sBJDIrafVkpRTicmPgXSjHw0W4MKXEvvAgVjxD+6FkSXUf04E9k4opSIPxBhOl1NIVSCsLhRDagWPaa2mwCGgT67RUKnYlOGqCTp1uIfL4X4S9DWQnUcBiBRNmmF0IDMcvnI0y3o+xaImERCkWzT3cDQ04AOXGxAb2Ql1HnqSix2MTxQkgDUKhIH2p40DbvUqPfpYmraoW2rKlJCIhEknR2RbNjUJt9aWi2AUWBI5kCpODkySG6u4dzrTaMbgDKNmMX9iFeCpeykEXzcNeudmQ9Qgi6uqKcPh3NrsthpykPp0H64/QFhYDunhgtRweQ45SWHgqqkYNRtRX6hFAK98ILMcvmT7l7T9flSHMfAwMJuwVFdX0dySmgg0BX+iCesPjww9C4bjaS5BPj3kaBQgQq8a+9AQyXo0oNDSX4+OPu7ClPu7YgR/mgKQGyXaBFQ0oVIgSHP+vj+Bdh+/xntLIGwEKNvFAKJQ18627BXXeuI+uRUnCkuZ/mlv5s93ovO2bOGiCbhoEXgSTatPv6Yux7q4NEYqLGqYw7jYBKrbh6V11LYN2tjoNzNJrkzTc7GBoa414vOR5xTnOg+AZwaKSSgv37T9PU1DPGilLBisydFemzVhI8RfjO/x4l37gfqTOEUwckOHgwxD8/6c6+9n5tQY41ZUA2N+sEnkjfHSFgcDDBn176klAoOtbVlJVKeFlJEALpL8ez7FJKr/kFJVt+iPSWOIIjpeDEiUH+8nIbw8NJ+0fDehm8n2mssE53VeN5vSa2JV3ZlpYBXvjjF9x5xzn4fEZqZCzAs+wyzNIakC5kcR2u6kbM8oUIVwBU0jGc3t4Yu587np3/QW+2emWa7XO+Nm9LX14J/AHIpBSFgG3b6rn5pkV4vWaqV0mvcY3JPTubNEkp6OuP8fTTrbz3fleubMKf9bJPd/qEEytyvPTcuHwnQihMI3nMUtIFXJp2WaXg2LEwAwNxlp1TjM+nIdlfzpeqkDI1IHz6mVb+/o/T46VaVupVjbd1sMbJMrRjQM1HdtO4fAeWZQB8CFQD67Ft4z12PExb+yD1dX4qKtwOckZjwSgFTYd6ePLJFj5t6pmszLVAhd4SM+wE0kzuDwrqZeib7Z9blqKy0su3rqjlkkuqmVfpzZzPq4K691NK0dERYd9bHbz9Tif9/bHxx1yjpYAnhFAPKCUyk+x83W2mN1AFgUeAO+09ZDpQNzT42XjRPNavC1JX58frNTIrPmOmHiK17BWJJGhrH+SDD0IcOBCisyuaATcFKd3jPmDPROQDaTa24BUBPwV+rFOdGVlWanNBSYmbhQsCLF1azPz5AcrL3Xi9BlKm8trRSJIz3cO0tw/ScnSAtrZBwuF4xpqyNKw3jOYLaRfQN6eAckAygOuAn+Xa4ZreegepvT4ul8Q0JEKmICaTinjcymQqx9ntagF/A36r9ydelmdVH9OWNDyngMYBtQD4AXCb3jg+ruzDoDzc53Pgcb1XuhdYDjylN6hPpkF98/blA2gmNlCNUtZF24AHgW3Ao/rRgpypz3G2ANkV0btY79flPa7hAPwbuMu+y3UCBYCL8m3PrD6rkWMtfL6u3KV6tXMJUKpjSHrIoTTEKBACWvVjCO/o954JLrkS+N1kliQED1uWeOjVv247u4AmAIUO4LX6GY5KfSw0nD4N5z867zQmyWy3VHv5UlgrLSUngjQsBN9Rij1nJQY5AJW3JmrQ9uteI2m5MI1hlBKrQPxeb7LI1nPAfUD4KwdotnXtt/eSSJoY0kK720PanQPAGeAF4Jc6EzG33fxXRTkeqFmqt8B0Asfsk8D/S0Dk6cpn8zHPggoqqKCCCiqooIL+B/RfSfObWejlE8oAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDEtMjdUMDk6NTE6MTgrMDA6MDBmD1f1AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTAxLTI3VDA5OjUxOjE4KzAwOjAwF1LvSQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wMS0yN1QwOTo1MjozMSswMDowMHzNNzsAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      deployments:
      - label:
          app: camel-monitor-operator
          app.kubernetes.io/component: operator
          app.kubernetes.io/name: camel-monitor
          app.kubernetes.io/version: 0.2.1
          camel.apache.org/component: operator
          name: camel-monitor-operator
        name: camel-monitor-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: camel-monitor-operator
              name: camel-monitor-operator
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                app: camel-monitor-operator
                app.kubernetes.io/component: operator
                app.kubernetes.io/name: camel-monitor
                app.kubernetes.io/version: 0.2.1
                camel.apache.org/component: operator
                name: camel-monitor-operator
            spec:
              containers:
              - command:
                - camel-monitor
                - operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: camel-monitor
                - name: OPERATOR_ID
                  value: camel-monitor
                - name: CREATE_PROMETHEUS_POD_MONITOR
                  value: "true"
                - name: CREATE_PROMETHEUS_RULE
                  value: "true"
                - name: CREATE_GRAFANA_DASHBOARD
                  value: "true"
                - name: GRAFANA_DS
                  value: prometheus
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/camel-tooling/camel-monitor-operator:0.2.1
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 20
                  periodSeconds: 10
                name: camel-monitor-operator
                ports:
                - containerPort: 8080
                  name: metrics
                resources:
                  limits:
                    cpu: "1"
                    memory: 1Gi
                  requests:
                    cpu: 250m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
              serviceAccountName: camel-monitor-operator
      permissions:
      - rules:
        - apiGroups:
          - camel.apache.org
          resources:
          - camelmonitors
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
        - apiGroups:
          - camel.apache.org
          resources:
          - camelmonitors/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - get
          - list
          - watch
        - apiGroups:
          - grafana.integreatly.org
          resources:
          - grafanadashboards
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - camel.apache.org
          resources:
          - camelmonitors/finalizers
          verbs:
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - podmonitors
          - prometheusrules
          verbs:
          - create
          - get
          - list
          - update
          - watch
        serviceAccountName: camel-monitor-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apache
  - camel
  - dashboard
  - kubernetes
  - monitoring
  - microservices
  - integration
  - observability
  labels:
    name: camel-monitor-operator
  links:
  - name: Camel Monitor operator source code repository
    url: https://github.com/camel-tooling/camel-monitor-operator
  maintainers:
  - email: pcongiusti@apache.org
    name: Pasquale Congiusti
  maturity: alpha
  provider:
    name: Camel Tooling team
  selector:
    matchLabels:
      name: camel-monitor-operator
  version: 0.2.1
