apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simplyblock-operator
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: simplyblock-operator-simplyblock-aggregate-to-view
rules:
- apiGroups:
  - storage.simplyblock.io
  resources:
  - storageclusters
  - storagepools
  - storageclusters/status
  - storagepools/status
  verbs:
  - get
  - list
  - watch
