apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 1.9.0
  name: dynatrace-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      internal.dynatrace.com/app: webhook
      internal.dynatrace.com/component: webhook
