apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocp-kea-dhcp
  name: ocp-kea-dhcp-keacontrolagent-viewer-role
rules:
- apiGroups:
  - kea.openshift.io
  resources:
  - keacontrolagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kea.openshift.io
  resources:
  - keacontrolagents/status
  verbs:
  - get
