apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: platform-billing-operator-billing-provider
rules:
- apiGroups:
  - billing.opendatahub.io
  resources:
  - pricebooks
  - plans
  - tenantaccounts
  - reservations
  - budgetpolicies
  - billingconnectors
  verbs:
  - list
  - watch
