apiVersion: v1
data:
  images.json: |
    {
        "controlPlaneAgents": {
          "1.4.1": {
            "dbinit": "sha256:148886c2e97c0f9031afcb957df431fadbf4b867aa0ef051156e30341dd0b9dd",
            "backupinit": "sha256:047e7c22b2559678fc9fcc848db16d39c0213323b49316e749c26ed4d0f06e81",
            "logrotate": "sha256:a0e21b2cd6513df3554c4dce459fdbf2cb1a9b2d2a311159f542cabe780f82c5",
            "monitoring-agent": "sha256:dff647adfacdb1d2b5598267ff5b60a96c7c2ba735607bbe5907b3f8debb603b"
          }
        },
        "dataPlane": {
          "15.7.1": {
            "database": "sha256:a5bed2940b31510635e553f940bea26fa1b186971a0af21e2653436af414f594"
          }
        }
      }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    alloydbomni.internal.dbadmin.goog/release-version: 1.4.1
    alloydbomni.internal.dbadmin.goog/task-type: image-catalog
  name: fleet-alloydb-omni-images-1.4.1
