apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: ghcr.io/vyogotech/frappe-operator:v4.1.0
    alm-examples: |-
      [
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "FrappeBench",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "frappebench-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "frappebench",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "frappebench-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteRestore",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "siterestore-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "siterestore",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "siterestore-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "FrappeSite",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "frappesite-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "frappesite",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "frappesite-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "FrappeWorkpace",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "frappeworkpace-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "frappeworkpace",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "frappeworkpace-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteBackup",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "sitebackup-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sitebackup",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "sitebackup-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteDashboard",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "sitedashboard-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sitedashboard",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "sitedashboard-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteDashboardChart",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "sitedashboardchart-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sitedashboardchart",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "sitedashboardchart-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteJob",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "sitejob-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sitejob",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "sitejob-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteUser",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "siteuser-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "siteuser",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "siteuser-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "vyogo.tech/v1",
          "kind": "SiteWorkspace",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "frappe-operator",
              "app.kubernetes.io/instance": "siteworkspace-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "siteworkspace",
              "app.kubernetes.io/part-of": "frappe-operator"
            },
            "name": "siteworkspace-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    categories: Application Runtime,Database
    createdAt: "2026-05-08T02:51:31Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: frappe-operator.v4.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FrappeBench is the Schema for the frappebenches API
      displayName: Frappe Bench
      kind: FrappeBench
      name: frappebenches.vyogo.tech
      version: v1
    - description: FrappeSite is the Schema for the frappesites API
      displayName: Frappe Site
      kind: FrappeSite
      name: frappesites.vyogo.tech
      version: v1
    - description: FrappeWorkpace is the Schema for the frappeworkpaces API
      displayName: Frappe Workpace
      kind: FrappeWorkpace
      name: frappeworkpaces.vyogo.tech
      version: v1
    - description: SiteBackup is the Schema for the sitebackups API
      displayName: Site Backup
      kind: SiteBackup
      name: sitebackups.vyogo.tech
      version: v1
    - description: SiteDashboardChart is the Schema for the sitedashboardcharts API
      displayName: Site Dashboard Chart
      kind: SiteDashboardChart
      name: sitedashboardcharts.vyogo.tech
      version: v1
    - description: SiteDashboard is the Schema for the sitedashboards API
      displayName: Site Dashboard
      kind: SiteDashboard
      name: sitedashboards.vyogo.tech
      version: v1
    - description: SiteJob is the Schema for the sitejobs API
      displayName: Site Job
      kind: SiteJob
      name: sitejobs.vyogo.tech
      version: v1
    - description: SiteRestore is the Schema for the siterestores API
      displayName: Site Restore
      kind: SiteRestore
      name: siterestores.vyogo.tech
      version: v1
    - description: SiteUser is the Schema for the siteusers API
      displayName: Site User
      kind: SiteUser
      name: siteusers.vyogo.tech
      version: v1
    - description: SiteWorkspace is the Schema for the siteworkspaces API
      displayName: Site Workspace
      kind: SiteWorkspace
      name: siteworkspaces.vyogo.tech
      version: v1
  description: |
    The Frappe Operator brings the robust capabilities of Frappe and ERPNext frameworks natively into Kubernetes using the Operator Pattern.

    ### Features
    * **FrappeBench Provisioning**: Automatically deploy and scale custom Frappe stacks natively.
    * **Database Harmonization**: Spin up shared or dedicated MariaDB instances tailored.
    * **Automated Replicas**: High Availability web worker routing via Ingress.
    * **GitOps Compliance**: Designed to operate smoothly with ArgoCD.

    ### Setup
    Ensure that you have deployed the prerequisites in your cluster before bootstrapping an ERPNext portal using standard `kubectl apply` commands.
  displayName: Frappe Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAABCFBMVEX69vL39PH28/H18/H18vH08vH08vDz8vHy8fDx8fDx8PDw8PDt7+/s7+/r7e/q7e7p7e7n7O7n7O3m7O3l6+3h6ezg6Ozd5+vb5uvU4unT4enR4enR4ejQ4OjI3ObF2+XE2uXD2uXC2eXB2eTA2OS/2OS+1+S+1+O91uO41OK10+Kz0eGkyt2cxtyXw9uUwtqTwdqRwdmRwNmQwNmPv9mNv9iNvtiMvthwsNFtr9BsrtBrrtBrrdBqrdBqrc9prc9qrNBprM9orM9nrM9nq89mq89hqM1gqM1fp81ep81cpsxbpsxbpcxapcxZpcxZpMxZpMtYpMtWpMtWo8tVo8tWostVostUossFIrsWAAABkUlEQVR42u3ayVLCQBAG4JAYMuICIu5bjBh3UeKGorhjDIiKwvu/icekarrKcbqMWPX/Jw7d8IWaQ0+qjZE/jgEAAAAAEH8UlmpMh/oqvf4YIKb9smL8BUH8vl5/DLD8z5ZielVTBmj2JwDlVlMx7QoF0OsHAAAAAAAAAAAAACA5E3YjxXwckjOhVn9iKp7yXMV4c9RUrNevdS+wmPcCy8HVDAAAAAAAAAAAAOAHgCHmSCZ4gOHC/lEg5XTHlkudpRO5Mjied1gAUXroyK9a++qvaruexQTUQ9bFJHIBAAAAAAAAAAAA/hGAGioz+evnUMrbAQVYf5Urw5dlg7U/sLZ1dl6TcrtHPJbl3siVtcbuKm9/4H1jbELOOPVnjhKFhZn7Dm9/IFrJCDk5CpAjCrOT350hg3uIuIcYAAAAAAAAAAAAQG8iUk62yAZs5kuMFGcvmYDm3UWdk6tH7grHU8jLr+yQcAMAAAAAAAAAAAAwqAC/104p/YACOIvVSkoJtm3yZbWZWmwssQAAAAADBPgCbnRBE1ZmtlgAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - persistentvolumeclaims
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - k8s.mariadb.com
          resources:
          - databases
          - grants
          - mariadbs
          - users
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - keda.sh
          resources:
          - scaledobjects
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - keda.sh
          resources:
          - scaledobjects/finalizers
          verbs:
          - update
        - apiGroups:
          - keda.sh
          resources:
          - scaledobjects/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingressclasses
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - vyogo.tech
          resources:
          - frappebenches
          - frappesites
          - frappeworkpaces
          - sitebackups
          - sitedashboardcharts
          - sitedashboards
          - sitejobs
          - siterestores
          - siteusers
          - siteworkspaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - vyogo.tech
          resources:
          - frappebenches/finalizers
          - frappesites/finalizers
          - frappeworkpaces/finalizers
          - sitebackups/finalizers
          - sitedashboardcharts/finalizers
          - sitedashboards/finalizers
          - sitejobs/finalizers
          - siterestores/finalizers
          - siteusers/finalizers
          - siteworkspaces/finalizers
          verbs:
          - update
        - apiGroups:
          - vyogo.tech
          resources:
          - frappebenches/status
          - frappesites/status
          - frappeworkpaces/status
          - sitebackups/status
          - sitedashboardcharts/status
          - sitedashboards/status
          - sitejobs/status
          - siterestores/status
          - siteusers/status
          - siteworkspaces/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: frappe-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: frappe-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: frappe-operator
          control-plane: controller-manager
        name: frappe-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ghcr.io/vyogotech/frappe-operator:v4.1.0
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: frappe-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: frappe-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - frappe
  - erpnext
  - operator
  links:
  - name: Frappe Operator
    url: https://github.com/vyogotech/frappe-operator
  maintainers:
  - email: mallamrakesh@gmail.com
    name: rakeshkumarmallam
  - email: info@vyogo.tech
    name: varkrish
  maturity: alpha
  minKubeVersion: 1.23.0
  provider:
    name: Vyogo Tech
    url: https://vyogo.tech
  version: 4.1.0
  replaces: frappe-operator.v4.0.0
