apiVersion: v1
data:
  defaultDomainSuffix: .myplatform.com
  defaultFrappeImage: ghcr.io/vyogotech/frappe_base:latest
  defaultMariaDBImage: docker.io/library/mariadb:10.6
  defaultNginxImage: docker.io/library/nginx:1.25-alpine
  defaultPostgresImage: docker.io/library/postgres:15-alpine
  defaultRedisImage: docker.io/library/redis:7-alpine
  fpmCliPath: /usr/local/bin/fpm
  fpmRepositories: |
    [
      {
        "name": "frappe-community",
        "url": "https://fpm.frappe.io",
        "priority": 100
      }
    ]
  gitEnabled: "false"
  ingressControllerNamespace: ingress-nginx
  ingressControllerService: ingress-nginx-controller
  maxConcurrentSiteReconciles: "10"
kind: ConfigMap
metadata:
  name: frappe-operator-frappe-operator-config
