apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: redkey-operator
    control-plane: controller-manager
  name: redkey-operator-controller-manager-metrics-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: redkey-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
