apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubezap
    control-plane: controller-manager
  name: kubezap-controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: kubezap
    control-plane: controller-manager
status:
  loadBalancer: {}
