apiVersion: v1
kind: Service
metadata:
  name: coraza-kubernetes-operator
  labels:
    app.kubernetes.io/name: coraza-kubernetes-operator
    app.kubernetes.io/instance: coraza-kubernetes-operator
    control-plane: coraza-controller-manager
spec:
  type: ClusterIP
  ports:
  - name: http-ruleset-cache-server
    port: 80
    protocol: TCP
    targetPort: 18080
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: coraza-kubernetes-operator
    app.kubernetes.io/instance: coraza-kubernetes-operator
    control-plane: coraza-controller-manager
