apiVersion: v1
kind: Service
metadata:
  name: integration-console-plugin
  labels:
    app: integration-console-plugin
    app.kubernetes.io/part-of: integration-platform
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: integration-console-plugin-cert
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: integration-console-plugin
