apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: litellm-operator
  name: litellm-operator-litellminstance-admin-role
rules:
- apiGroups:
  - litellm.palena.ai
  resources:
  - litellminstances
  verbs:
  - '*'
- apiGroups:
  - litellm.palena.ai
  resources:
  - litellminstances/status
  verbs:
  - get
