apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: valkey-operator
  name: valkey-admin-role
rules:
- apiGroups:
  - cache.keiailab.io
  resources:
  - valkeys
  verbs:
  - '*'
- apiGroups:
  - cache.keiailab.io
  resources:
  - valkeys/status
  verbs:
  - get
