apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: organizationimmutabilities.quay.herve4m.github.io
spec:
  group: quay.herve4m.github.io
  names:
    kind: OrganizationImmutability
    plural: organizationimmutabilities
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Namespace in Quay
      jsonPath: .spec.namespace
      name: Quay namespace
      type: string
    - description: The status of the resource creation process in Quay
      jsonPath: .status.conditions[?(@.type == 'Successful')].status
      name: Success
      type: string
    - description: The error message when the resource creation process fails
      jsonPath: .status.message
      name: Message
      type: string
    - description: The state of the reconciliation process
      jsonPath: .status.conditions[?(@.type == 'Running')].reason
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Manage tag immutability policies for organizations and user namespaces
        properties:
          apiVersion:
            description: |
              APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |
              Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of OrganizationImmutability
            properties:
              behavior:
                description: Specify the behavior of the matching pattern. If 'matching_immutable',
                  then tags that match the pattern are immutable. If 'not_matching_immutable',
                  then all the tags not matching the pattern are immutable. 'matching_immutable'
                  by default.
                enum:
                - matching_immutable
                - not_matching_immutable
                type: string
              connSecretRef:
                description: |
                  Reference to the secret resource that stores the connection parameters to the Quay Container Registry API.
                  The secret must include the 'host', 'token' (or 'username' and 'password'), and optionally the 'validateCerts' keys.
                properties:
                  name:
                    description: Name of the secret resource.
                    type: string
                  namespace:
                    description: |
                      Namespace of the secret resource. By default, the secret resource is retrieved from the same namespace as the current OrganizationImmutability resource.
                    type: string
                required:
                - name
                type: object
              namespace:
                description: Organization or personal namespace. This namespace must
                  exist.
                type: string
              newTagPattern:
                description: New regular expression for the immutability policy. Setting
                  this option changes the regular expression of the policy which current
                  pattern is provided in 'tagPattern'.
                type: string
              preserveInQuayOnDeletion:
                default: false
                description: |
                  Whether to preserve the corresponding Quay object when you delete the OrganizationImmutability resource. When set to 'false' (the default), the object is deleted from Quay.
                type: boolean
              tagPattern:
                description: Regular expression to select the tags to protect.
                type: string
            required:
            - connSecretRef
            - namespace
            - tagPattern
            type: object
          status:
            description: |
              Status defines the observed state of OrganizationImmutability
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
