apiVersion: v1
kind: Service
metadata:
  name: openshift-integration-operator
  labels:
    app.kubernetes.io/name: openshift-integration-operator
    app.kubernetes.io/part-of: integration-platform
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: openshift-integration-operator-serving-cert
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: openshift-integration-operator
