apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oc-mirror
  name: oc-mirror-worker
