apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: langfuse-operator
  name: langfuse-operator-langfuseorganization-editor-role
rules:
- apiGroups:
  - langfuse.palena.ai
  resources:
  - langfuseorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - langfuse.palena.ai
  resources:
  - langfuseorganizations/status
  verbs:
  - get
