apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: virt-git-sync
  name: virt-git-sync-virtgitsync-viewer-role
rules:
- apiGroups:
  - virt.mathianasj.github.com
  resources:
  - virtgitsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virt.mathianasj.github.com
  resources:
  - virtgitsyncs/status
  verbs:
  - get
