apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-mappings: |
      properties:
        spec:
          properties:
            v20250312:
              x-atlas-sdk-version: go.mongodb.org/atlas-sdk/v20250312018/admin
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: mongodb-atlas-kubernetes-operator
    app.kubernetes.io/name: mongodb-atlas-kubernetes-operator
  name: groups.atlas.generated.mongodb.com
spec:
  group: atlas.generated.mongodb.com
  names:
    categories:
    - atlas
    kind: Group
    listKind: GroupList
    plural: groups
    shortNames:
    - ag
    singular: group
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    - jsonPath: .status.conditions[?(@.type=="State")].reason
      name: State
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: A group, managed by the MongoDB Kubernetes Atlas Operator.
        properties:
          spec:
            description: |-
              Specification of the group supporting the following versions:

              - v20250312

              At most one versioned spec can be specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
            properties:
              connectionSecretRef:
                description: |-
                  SENSITIVE FIELD

                  Reference to a secret containing the credentials to setup the connection to Atlas.
                properties:
                  name:
                    description: Name of the secret containing the Atlas credentials.
                    type: string
                type: object
              v20250312:
                description: The spec of the group resource for version v20250312.
                properties:
                  entry:
                    description: The entry fields of the group resource spec. These
                      fields can be set for creating and updating groups.
                    properties:
                      name:
                        description: Human-readable label that identifies the project
                          included in the MongoDB Cloud organization.
                        type: string
                      orgId:
                        description: Unique 24-hexadecimal digit string that identifies
                          the MongoDB Cloud organization to which the project belongs.
                        example: 32b6e34b3d91647abb20e7b8
                        type: string
                      regionUsageRestrictions:
                        description: |-
                          Applies to Atlas for Government only.

                          In Commercial Atlas, this field will be rejected in requests and missing in responses.

                          This field sets restrictions on available regions in the project.

                          `COMMERCIAL_FEDRAMP_REGIONS_ONLY`: Only allows deployments in FedRAMP Moderate regions.

                          `GOV_REGIONS_ONLY`: Only allows deployments in GovCloud regions.
                        type: string
                      tags:
                        description: List that contains key-value pairs between 1
                          to 255 characters in length for tagging and categorizing
                          the project.
                        items:
                          description: 'Key-value pair that tags and categorizes a
                            MongoDB Cloud organization, project, or cluster. For example,
                            `environment : production`.'
                          properties:
                            key:
                              description: 'Constant that defines the set of the tag.
                                For example, `environment` in the `environment : production`
                                tag.'
                              type: string
                            value:
                              description: 'Variable that belongs to the set of the
                                tag. For example, `production` in the `environment
                                : production` tag.'
                              type: string
                          required:
                          - key
                          - value
                          title: Resource Tag
                          type: object
                        type: array
                      withDefaultAlertsSettings:
                        description: Flag that indicates whether to create the project
                          with default alert settings.
                        type: boolean
                    required:
                    - name
                    - orgId
                    type: object
                  projectOwnerId:
                    description: Unique 24-hexadecimal digit string that identifies
                      the MongoDB Cloud user to whom to grant the Project Owner role
                      on the specified project. If you set this parameter, it overrides
                      the default value of the oldest Organization Owner.
                    type: string
                    x-kubernetes-validations:
                    - message: projectOwnerId cannot be modified after creation
                      rule: self == oldSelf
                type: object
            type: object
          status:
            description: 'Most recently observed read-only status of the group for
              the specified resource version. This data may not be up to date and
              is populated by the system. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
            properties:
              conditions:
                description: Represents the latest available observations of a resource's
                  current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon.
                      type: integer
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition.
                      type: string
                  required:
                  - type
                  - status
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              v20250312:
                description: The last observed Atlas state of the group resource for
                  version v20250312.
                properties:
                  clusterCount:
                    description: Quantity of MongoDB Cloud clusters deployed in this
                      project.
                    type: integer
                  created:
                    description: Date and time when MongoDB Cloud created this project.
                      This parameter expresses its value in the ISO 8601 timestamp
                      format in UTC.
                    type: string
                  id:
                    description: Unique 24-hexadecimal digit string that identifies
                      the MongoDB Cloud project.
                    example: 32b6e34b3d91647abb20e7b8
                    type: string
                required:
                - clusterCount
                - created
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
