apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oci-capi-autoscaling-operator
  name: oci-capi-operator-ociclusterautoscaler-editor-role
rules:
- apiGroups:
  - capi.openshift.io
  resources:
  - ociclusterautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capi.openshift.io
  resources:
  - ociclusterautoscalers/status
  verbs:
  - get
