apiVersion: v1
data:
  API_SERVER_LOAD_BALANCER_ID: ${API_LB_ID}
  AUTOSCALER_CPUS: ${AUTOSCALER_CPUS}
  AUTOSCALER_DEFINED_TAGS_NAMESPACE: ${AUTOSCALER_DEFINED_TAGS_NAMESPACE}
  AUTOSCALER_DISCOVERY_NAMESPACE: ${AUTOSCALER_DISCOVERY_NAMESPACE}
  AUTOSCALER_MAX_NODES: ${AUTOSCALER_MAX_NODES}
  AUTOSCALER_MEMORY: ${AUTOSCALER_MEMORY}
  AUTOSCALER_MIN_NODES: ${AUTOSCALER_MIN_NODES}
  AUTOSCALER_NAMESPACE: ${AUTOSCALER_NAMESPACE}
  AUTOSCALER_SHAPE: ${AUTOSCALER_SHAPE}
  BARE_METAL_SUBNET_ID: ${BARE_METAL_SUBNET_ID}
  BARE_METAL_SUBNET_NAME: ${BARE_METAL_SUBNET_NAME}
  CAPI_PROVIDER_NAMESPACE: ${CAPI_PROVIDER_NAMESPACE}
  CAPI_VERSION: ${CAPI_VERSION}
  CAPOCI_PROVIDER_NAMESPACE: ${CAPOCI_PROVIDER_NAMESPACE}
  CAPOCI_VERSION: ${CAPOCI_VERSION}
  CLUSTER_NETWORK_CIDR_BLOCK: ${CLUSTER_CIDR}
  COMPARTMENT_ID: ${COMPARTMENT_ID}
  COMPUTE_NSG_NAME: ${COMPUTE_NSG_NAME}
  CONTROL_PLANE_ENDPOINT: ${API_LB_IP}
  CSR_MACHINE_NAMESPACE: ${MANAGED_RESOURCE_NAMESPACE}
  IMAGE_ID: ${IMAGE_ID}
  MANAGED_RESOURCE_NAMESPACE: ${MANAGED_RESOURCE_NAMESPACE}
  NETWORK_SECURITY_GROUP_ID: ${NSG_ID}
  OCI_REGION: ${OCI_REGION}
  OCI_TENANCY_ID: ${OCI_TENANCY_ID}
  OCI_USE_INSTANCE_PRINCIPAL: ${OCI_USE_INSTANCE_PRINCIPAL}
  OCI_USER_ID: ${OCI_USER_ID}
  OCP_SUBNET_ID: ${OCP_SUBNET_ID}
  OCP_SUBNET_NAME: ${OCP_SUBNET_NAME}
  SERVICE_NETWORK_CIDR_BLOCK: ${SVC_CIDR}
  VCN_ID: ${VCN_ID}
kind: ConfigMap
metadata:
  name: oci-capi-operator-config
